version: '2'
services:
  tl-mariadb:
    container_name: tl-mariadb
    image: bitnami/mariadb:latest
    ports:
      - "3306:3306"  # Corrected syntax
    volumes:
      - tl-mariadb-data:/bitnami/mariadb
      #- ./tl_testlink_backup_utf8.sql:/docker-entrypoint-initdb.d/tl_testlink_backup_utf8.sql
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=tl_testlink
      - MARIADB_DATABASE=tl_testlink
      - MARIADB_ROOT_PASSWORD=YourRootPasswordHere  # Set your desired root password here
      - MARIADB_SSL_CERT_FILE=/certs/certificate.crt  # Specify SSL certificate file
      - MARIADB_SSL_KEY_FILE=/certs/private.key        # Specify SSL key file
      - MARIADB_SSL_CA_FILE=/certs/ca_bundle.crt       # Specify CA bundle file
    networks:
      - testlink-net

  tl-testlink:
    container_name: tl-testlink
    image: bitnami/testlink-archived
    ports:
      - 83:8080
      - 444:8443
      - 443:443 # SSL port
    volumes:
      - tl-testlink-data:/bitnami/testlink
      - D:\repo\testlink\certs:/etc/apache2/ssl
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - TESTLINK_DATABASE_HOST=tl-mariadb
      - TESTLINK_DATABASE_PORT_NUMBER=3306
      - TESTLINK_DATABASE_USER=tl_testlink
      - TESTLINK_DATABASE_NAME=tl_testlink
      - TESTLINK_USERNAME=admin
      - TESTLINK_PASSWORD=Nasru@2022
      - TESTLINK_EMAIL=khazi.devops@gmail.com
      - SMTP_ENABLE=true
      - SMTP_HOST=smtp.gmail.com
      - SMTP_USER=khazi.devops@gmail.com
      - SMTP_PASSWORD=ifcqfdcnoraexgtl
      - SMTP_PORT=587
      - SMTP_CONNECTION_MODE=tls
    depends_on:
      - tl-mariadb
    networks:
      - testlink-net

networks:
  testlink-net:

volumes:
  tl-mariadb-data:
  tl-testlink-data:
